language: rust
script: cargo test --all-features --all

jobs:
  include:
  - rust: 1.33.0
    script: |
      cargo update &&
      cargo update -p unicode-normalization --precise 0.1.9 &&
      cargo test --all-features --all &&
      cargo update
  - rust: stable
  - rust: beta
  - rust: nightly
  - rust: nightly
    env: TARGET=WASM32  # For job list UI
    install: rustup target add wasm32-unknown-unknown
    script: cargo build --all --target=wasm32-unknown-unknown
